### ISSUE TITLE
Не открывается "Демо лояльность" на Android 10 и выше

### ISSUE THREAD

**Issue by Exzept1on** [modulkassa/android-integration-sdk#65]
### Ожидаемое поведение

После нажатия на кнопку с "%", которое открывает меню "скидка" в приложении "МодульКасса" и выбора системы лояльности, например "Демо лояльность",  из текущего репозитория или любое другое, откроется приложение "Демо лояльность" или любое другое соответственно.

### Фактическое поведение

После нажатия кнопки, после которой должно открыться приложение, ничего не происходит, просто вечный экран загрузки.

### Действия по воспроизведению

1. Накатываем 10 андроид или выше на кассу.
2. Ставим приложение "МодульКасса" на кассу.
3. Ставим, например приложение "Демо лояльность" из тек. репозитория по инструкции.
4. Открываем приложение.
5. Логинимся.
6. Выбираем любой товар.
7. Переходим к оплате.
8. Используем кнопку "%" для выбора скидки.
9. Выбираем на странице со скидками "Демо лояльность".
10. Получаем бесконечную загрузку.

### Дополнительная информация

Если "Демо лояльность" или любую другую лояльность, запустить в фоне и только потом выбрать ее в приложении "МодульКасса", то все отработает как следует. Следует эта ошибка из-за нововведений андройда 10, который запрещает сервисам запускать активити. Для этого есть исправления, а точнее нужно изменить способ запуска приложений из списка "скидки", но это вы уже сами решайте, как править, возможно есть вариант с исправлением на стороне интеграций.

Версия приложения "МодульКасса": 8.82.0

**Comment by AnastasiaKoreshkova** [comment]
Добрый день! Данное поведение было исправлено нами в релизе Модулькассы 8.86.0 в мае этого года.

**Comment by Exzept1on** [comment]
Обновились до последней возможной версии: 8.89.0, к сожалению проблема не решилась. Все также, необходимо запустить приложение сторонней лояльности в фоне, а только потом уже использовать кнопку запуска приложения сторонней системы лояльности в приложении кассы, такое происходит как с собственным приложением лояльности, так и с тем, что есть в тек. репозитории.

**Comment by Exzept1on** [comment]
Получили инфу от ТП "МодульКассы", о том, что разработчики сторонних систем лояльности должны исправить сию фичу андроида на своей стороне. Закрываю это.
